version: "3.8"

services:
  job-manager:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink_job-manager
    ports:
      - "8081:8081"   # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
    command: jobmanager
    volumes:
      - ./conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    networks:
      - flink-net

  task-manager1:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink_task-manager1
    depends_on:
      - job-manager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
      - TASK_MANAGER_HEAP_SIZE=1024m
    command: taskmanager
    volumes:
      - ./conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    networks:
      - flink-net

  task-manager2:
    image: flink:1.20.3-scala_2.12-java17
    container_name: flink_task-manager2
    depends_on:
      - job-manager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job-manager
      - TASK_MANAGER_HEAP_SIZE=1024m
    command: taskmanager
    volumes:
      - ./conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    networks:
      - flink-net

networks:
  flink-net:
    driver: bridge
